import { Type } from '@sinclair/typebox';
import type { FastifyPluginAsyncTypebox } from '@fastify/type-provider-typebox';
import { createOrderService } from '@services/create-order/index.js';

/**
 * CreateOrder Routes
 * 
 * Demonstrates the Golden Orchestrator pattern.
 * Uses CreateOrderService which implements the pipeline pattern.
 * 
 * Generated by: npm run generate
 */
const createOrderRoutes: FastifyPluginAsyncTypebox = async (fastify) => {
  // Create CreateOrder - Uses Golden Orchestrator Pattern
  fastify.post(
    '/',
    {
      preValidation: [fastify.authenticate],
      schema: {
        description: 'Create a new createOrder',
        tags: ['CreateOrders'],
        security: [{ bearerAuth: [] }],
        body: Type.Object({
          // TODO: Define your request body schema
          name: Type.String({ minLength: 1 }),
        }),
        response: {
          201: Type.Object({
            success: Type.Literal(true),
            data: Type.Object({
              id: Type.String(),
              createdAt: Type.String({ format: 'date-time' }),
              updatedAt: Type.String({ format: 'date-time' }),
              // TODO: Add your fields
            }),
            metadata: Type.Optional(Type.Object({
              duration: Type.Number({ description: 'Total execution time in ms' }),
              metrics: Type.Optional(Type.Record(Type.String(), Type.Number())),
            })),
          }),
          400: Type.Object({
            success: Type.Literal(false),
            error: Type.Object({
              message: Type.String(),
              statusCode: Type.Number(),
            }),
          }),
        },
      },
    },
    async (request, reply) => {
      // Call the service - it uses the orchestrator internally
      const result = await createOrderService.createCreateOrder({
        // TODO: Map request body to input
        ...request.body,
      });

      if (!result.success) {
        return reply.status(400).send({
          success: false,
          error: {
            message: result.error?.message || 'Failed to create createOrder',
            statusCode: 400,
          },
        });
      }

      return reply.status(201).send({
        success: true,
        data: {
          ...result.data!,
          createdAt: result.data!.createdAt.toISOString(),
          updatedAt: result.data!.updatedAt.toISOString(),
        },
        metadata: {
          duration: result.duration,
          metrics: result.metrics,
        },
      });
    }
  );

  // Health check
  fastify.get(
    '/health',
    {
      schema: {
        description: 'Check if CreateOrder service is healthy',
        tags: ['CreateOrders'],
        response: {
          200: Type.Object({
            status: Type.String(),
            service: Type.String(),
          }),
        },
      },
    },
    async (_request, reply) => {
      const health = await createOrderService.healthCheck();
      return reply.send(health);
    }
  );

  // Get all createOrders (simple example)
  fastify.get(
    '/',
    {
      preValidation: [fastify.authenticate],
      schema: {
        description: 'Get all createOrders',
        tags: ['CreateOrders'],
        security: [{ bearerAuth: [] }],
        response: {
          200: Type.Object({
            success: Type.Literal(true),
            data: Type.Array(
              Type.Object({
                id: Type.String(),
                // TODO: Add your fields
              })
            ),
          }),
        },
      },
    },
    async (_request, reply) => {
      // TODO: Implement list logic (could create a ListOrchestrator)
      // For now, returning empty array
      return reply.send({
        success: true,
        data: [],
      });
    }
  );
};

export default createOrderRoutes;
